// @ts-check
// Tiny server-rendered pages (no client JavaScript at all, so a strict CSP with no inline script works).
const esc = (/** @type {string} */ s) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] || c);
const shell = (/** @type {string} */ title, /** @type {string} */ body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><link rel="icon" href="data:,"><title>${esc(title)}</title><style>:root{--surface-body:#f9f9f7;--surface-primary:#fff;--surface-secondary:#efeee5;--text-primary:#16150f;--text-secondary:#605d53;--text-white:#fff;--border-default:#cbcac5;--action-default:#16150f;--action-hover:#32312c;--action-press:#1f1e19;--space-xs:8px;--space-md:16px;--space-xl:40px;--radius-sm:8px;--radius-lg:24px;--radius-full:999px;--opacity-disabled:.4}body{font:16px/1.5 system-ui,sans-serif;background:var(--surface-body);color:var(--text-primary);margin:0;display:grid;place-items:center;min-height:100vh}main{background:var(--surface-primary);border:1px solid var(--border-default);border-radius:var(--radius-lg);padding:var(--space-xl);max-width:420px;width:calc(100% - 32px)}h1{font-size:24px;margin:0 0 var(--space-xs)}p{color:var(--text-secondary)}input,button{font:inherit;height:48px;padding:0 var(--space-md);border-radius:var(--radius-sm);border:1px solid var(--border-default);width:100%;box-sizing:border-box;margin-top:var(--space-md)}button{background:var(--action-default);color:var(--text-white);cursor:pointer;border-color:transparent;border-radius:var(--radius-full);font-weight:600}button:hover{background:var(--action-hover)}button:active{background:var(--action-press)}button:disabled{opacity:var(--opacity-disabled);cursor:not-allowed}a{color:var(--text-primary)}.alt button.linklike{display:inline;width:auto;height:auto;padding:0;margin:0;border:none;background:none;color:var(--text-primary);text-decoration:underline;font-weight:400;border-radius:0}.alt button.linklike:hover{background:none}.alt{margin:0}.alt p{margin:var(--space-md) 0 0}.msg{color:var(--text-secondary);background:var(--surface-secondary);padding:var(--space-xs) var(--space-md);border-radius:var(--radius-sm)}</style></head><body><main>${body}</main></body></html>`;

/** Step 1: ask for the email. @param {{ message?: string }} [o] */
export function loginHtml(o = {}) {
  return shell('Sign in', `<h1>Cost tracker</h1><p>Enter your email to sign in. We send you a sign-in code, or ask for your password if you set one in Account. New accounts must be approved by an administrator before they can use the tracker.</p>${o.message ? `<p class="msg" role="status">${esc(o.message)}</p>` : ''}<form method="post" action="/auth/login"><input name="email" type="email" required autocomplete="email" placeholder="you@example.com"><button type="submit">Continue</button></form>`);
}
/** Step 2: ask for the code that was emailed. @param {{ email: string, message?: string }} o */
export function codeHtml(o) {
  return shell('Enter your code', `<h1>Check your email</h1><p>We sent a sign-in code to <strong>${esc(o.email)}</strong>. It can take a minute to arrive; check spam too.</p>${o.message ? `<p class="msg" role="status">${esc(o.message)}</p>` : ''}<form method="post" action="/auth/verify"><input name="code" required inputmode="numeric" autocomplete="one-time-code" pattern="[0-9 \\-]{6,13}" maxlength="13" placeholder="123456" aria-label="Sign-in code" autofocus><button type="submit">Sign in</button></form><p>Wrong address or no code? <a href="/login?restart=1">Start again</a></p>`);
}
/** Step 2 for accounts that chose a password (Account > Security). @param {{ email: string, message?: string }} o */
export function passwordHtml(o) {
  return shell('Enter your password', `<h1>Enter your password</h1><p>Signing in as <strong>${esc(o.email)}</strong>.</p>${o.message ? `<p class="msg" role="status">${esc(o.message)}</p>` : ''}<form method="post" action="/auth/password"><input name="password" type="password" required autocomplete="current-password" placeholder="Password" aria-label="Password" autofocus><button type="submit">Sign in</button></form><form method="post" action="/auth/login" class="alt"><input type="hidden" name="email" value="${esc(o.email)}"><input type="hidden" name="send_code" value="1"><p>Forgot your password? <button type="submit" class="linklike">Email me a sign-in code</button></p></form><p>Not you? <a href="/login?restart=1">Start again</a></p>`);
}
export function pendingHtml() {
  return shell('Waiting for approval', `<h1>Waiting for approval</h1><p>Your account exists, but an administrator has to approve it before you can use the tracker. Try again later.</p><form method="post" action="/auth/signout"><button type="submit">Sign out</button></form>`);
}
export function blockedHtml() {
  return shell('Account blocked', `<h1>Account blocked</h1><p>This account can't use the tracker.</p><form method="post" action="/auth/signout"><button type="submit">Sign out</button></form>`);
}
