// Writes the Okara Design System variables (tests/figma-tokens.json, read from Figma) into the token block of
// src/ui/okara.css, between the @tokens:start / @tokens:end markers. Run after updating the JSON from Figma.
//   node scripts/sync-tokens.mjs
// Names mirror Figma: Color/surface/primary -> --surface-primary, Spacing/space/xs -> --space-xs.
// Primitives get a --primitive- prefix (their names overlap the Color ones, e.g. data/blue) and the Color
// variables point at them with var(), exactly as the aliases in Figma do.
import { readFileSync, writeFileSync } from 'node:fs';

const tokens = JSON.parse(readFileSync(new URL('../tests/figma-tokens.json', import.meta.url), 'utf8'));
const cssPath = new URL('../src/ui/okara.css', import.meta.url);
const kebab = (name) => name.toLowerCase().replace(/\//g, '-');
export const cssName = (collection, name) => (collection === 'Primitives' ? '--primitive-' : '--') + kebab(name);
const units = { Spacing: 'px', Radius: 'px' };
// Typography variables hold a family name only; the CSS adds a fallback stack after it.
export const FONT_FALLBACK = {
  'font/sans': 'system-ui, -apple-system, "Segoe UI", sans-serif',
  'font/mono': 'ui-monospace, SFMono-Regular, Menlo, monospace',
};
// Text styles (Figma local text styles) become four custom properties each:
// Body/Small/Medium -> --type-body-small-medium-size / -weight / -lh / -ls. Letter spacing is a % in Figma, em here.
export const textStyleVars = (name, t) => {
  const k = '--type-' + kebab(name);
  return [[k + '-size', t.size + 'px'], [k + '-weight', String(t.weight)],
    [k + '-lh', t.lineHeight == null ? 'normal' : t.lineHeight + 'px'], [k + '-ls', t.letterSpacing ? t.letterSpacing / 100 + 'em' : '0']];
};
export const fontStack = (name, family) => `"${family}", ${FONT_FALLBACK[name] || 'sans-serif'}`;


const lines = ['    /* Generated by scripts/sync-tokens.mjs from tests/figma-tokens.json. Do not edit by hand. */'];
for (const [collection, vars] of Object.entries(tokens)) {
  if (collection.startsWith('_')) continue;
  lines.push('', `    /* Collection: ${collection} */`);
  if (collection === 'TextStyles') {
    for (const [name, t] of Object.entries(vars)) for (const [k, v] of textStyleVars(name, t)) lines.push(`    ${k}: ${v};`);
    continue;
  }
  for (const [name, value] of Object.entries(vars)) {
    let v;
    if (value && typeof value === 'object' && value.alias) v = `var(${cssName('Primitives', value.alias)})`;
    else if (typeof value === 'number') v = collection === 'Opacity' ? String(value > 1 ? value / 100 : value) : value + (units[collection] || '');
    else if (collection === 'Typography') v = fontStack(name, value);
    else v = value;
    const note = collection === 'Opacity' && typeof value === 'number' && value > 1 ? '   /* Figma stores this one as a percentage (24) */' : '';
    lines.push(`    ${cssName(collection, name)}: ${v};${note}`);
  }
}
const block = lines.join('\n');
const css = readFileSync(cssPath, 'utf8');
const start = css.indexOf('/* @tokens:start */'), end = css.indexOf('/* @tokens:end */');
if (start < 0 || end < 0) throw new Error('token markers not found in okara.css');
writeFileSync(cssPath, css.slice(0, start) + '/* @tokens:start */\n' + block + '\n    ' + css.slice(end));
console.log(`okara.css: ${lines.filter((l) => l.includes(': ')).length} variables written`);
